spring:
  application:
    name: virma
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/virma
    username: virma
    password: virma
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
nginx:
  server:
    url: http://192.168.1.38:9080